[profile.default]
solc-version = "0.8.17"
verbosity = 2
optimizer = false
# optimizer_runs = 20
# true for stack-too-deep error avoidance,
# off for speedy builds (if it compiles)
via_ir = true
bytecode_hash = "none"


[profile.default.optimizer_details]
constantOptimizer = true
yul = true
